ALTER TABLE users ADD COLUMN disabled boolean NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN mfa_secret bytea;
ALTER TABLE users ADD COLUMN mfa_enabled boolean NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN mfa_last_step bigint NOT NULL DEFAULT -1;
ALTER TABLE users ADD COLUMN recovery_hashes text[] NOT NULL DEFAULT '{}';
ALTER TABLE users ADD COLUMN oidc_subject text NOT NULL DEFAULT '';
CREATE UNIQUE INDEX users_oidc_subject ON users(oidc_subject) WHERE oidc_subject <> '';
ALTER TABLE cases ADD COLUMN token_version integer NOT NULL DEFAULT 1;
ALTER TABLE sessions ADD COLUMN token_version integer NOT NULL DEFAULT 1;
CREATE TABLE oidc_states(hash text PRIMARY KEY, browser_hash text NOT NULL, payload bytea NOT NULL, expires timestamptz NOT NULL);
CREATE TABLE evidence(id text PRIMARY KEY, case_ref text NOT NULL REFERENCES cases(ref) ON DELETE CASCADE, encrypted bytea NOT NULL, size bigint NOT NULL CHECK(size >= 0));
CREATE INDEX evidence_case ON evidence(case_ref);
CREATE TABLE notifications(id text PRIMARY KEY, dedupe text UNIQUE NOT NULL, case_ref text NOT NULL, recipient bytea NOT NULL, kind text NOT NULL, created timestamptz NOT NULL DEFAULT now(), available timestamptz NOT NULL DEFAULT now(), attempts integer NOT NULL DEFAULT 0, sent timestamptz, last_error text NOT NULL DEFAULT '', lease_until timestamptz, lease_token text NOT NULL DEFAULT '');
CREATE INDEX notifications_pending ON notifications(available) WHERE sent IS NULL;
CREATE TABLE rate_limits(key text PRIMARY KEY, started timestamptz NOT NULL, count integer NOT NULL);
CREATE INDEX cases_created ON cases((data->'Case'->>'Created'));
CREATE INDEX cases_owner ON cases((data->'Case'->>'Owner'));
CREATE INDEX cases_status ON cases((data->'Case'->>'Status'));
ALTER TABLE deployment_secrets ADD COLUMN IF NOT EXISTS oidc_issuer text NOT NULL DEFAULT '';
