name: release-candidate
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff
        with:
          go-version-file: go.mod
      - run: ./scripts/release.sh
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: beacon-candidate-unsigned
          path: artifacts/release/
          retention-days: 14
      - uses: actions/attest-build-provenance@96b4a1ef7235a096b17240c259729fdd70c83d45
        with:
          subject-path: artifacts/release/beacon-*
